import '../globals.css'
import Menu from '../Menu'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function TiendasLayout({ children }) {
  return (

    <>
      <Menu />
      {children}

    </>
  )
}

